# Generated by Django 5.2 for the profile import contract.

from django.db import migrations, models
from django.db.models import Q


def populate_source_order(apps, schema_editor):
    for model_name in ("Experience", "Education"):
        model = apps.get_model("profiles", model_name)
        records = model.objects.order_by("profile_id", "id")
        current_profile = None
        source_order = 0
        for record in records.iterator():
            if record.profile_id != current_profile:
                current_profile = record.profile_id
                source_order = 0
            record.source_order = source_order
            record.save(update_fields=["source_order"])
            source_order += 1


def normalize_legacy_empty_urls(apps, schema_editor):
    profile = apps.get_model("profiles", "Profile")
    profile.objects.filter(profile_url="").update(profile_url=None)


def restore_legacy_empty_urls(apps, schema_editor):
    profile = apps.get_model("profiles", "Profile")
    profile.objects.filter(profile_url__isnull=True).update(profile_url="")


class Migration(migrations.Migration):
    dependencies = [("profiles", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="raw_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="experience",
            name="source_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="education",
            name="source_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_source_order, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="profile_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(normalize_legacy_empty_urls, restore_legacy_empty_urls),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=Q(linkedin_id__isnull=False),
                fields=("linkedin_id",),
                name="profiles_profile_linkedin_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=Q(linkedin_username__isnull=False),
                fields=("linkedin_username",),
                name="profiles_profile_linkedin_username_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=Q(profile_url__isnull=False),
                fields=("profile_url",),
                name="profiles_profile_url_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.UniqueConstraint(
                fields=("profile", "source_order"),
                name="profiles_experience_profile_source_order_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="education",
            constraint=models.UniqueConstraint(
                fields=("profile", "source_order"),
                name="profiles_education_profile_source_order_unique",
            ),
        ),
    ]
